### ISSUE TITLE
No libmobiledevice (确认已安装，ios代理已连接成功4272代理，mitm证书已装)

### ISSUE THREAD

**Issue by NextOneWxf** [meituan/lyrebird-ios#2]
@zhaoye 
![image](https://user-images.githubusercontent.com/4550421/42988880-cf5613c0-8c30-11e8-88a8-22395f111c3f.png)
![image](https://user-images.githubusercontent.com/4550421/42988995-1c8fd162-8c31-11e8-83cf-3432e396647e.png)
![image](https://user-images.githubusercontent.com/4550421/42989013-279ab126-8c31-11e8-865e-a436a0235cbc.png)
   [有抓包数据]
![image](https://user-images.githubusercontent.com/4550421/42989024-31e12b56-8c31-11e8-8cf6-783c6a9d285b.png)

**Comment by YurRee** [comment]
1. 请您尝试将您的 iPhone 设备连接至 Mac，并信任。
2. 接下来终端输入如下命令
`$ ideviceinfo`

3. 如您看到如下输出，则表示依赖环境正常，此后，再次刷新 Lyrebird Plugin - iOS 首页 查看。
```zsh
ActivationState: Activated
ActivationStateAcknowledged: true
BasebandActivationTicketVersion: V2
BasebandCertId: 2315222105
...
```

希望能够为您提供有效的帮助，Thanks. 🎉

**Comment by NextOneWxf** [comment]
@YurRee 大佬 ubuntu可以玩么  我用的linuxbrew

**Comment by YurRee** [comment]
可以参考我们的建议 [环境要求](https://github.com/meituan/lyrebird-ios#%E7%8E%AF%E5%A2%83%E8%A6%81%E6%B1%82)

But，libmobiledevice 支持 Linux，理论上，是可以。

**Comment by YurRee** [comment]
可以参考 [libimobiledevice](http://www.libimobiledevice.org/) 获取更多关于 libimobiledevice 在不同系统上的支持信息。以下是部分引用
> Latest Release: 1.2.0
Tested with iPod Touch 1G/2G/3G/4G/5G/6G, iPhone 1G/2G/3G/3GS/4/4S/5/5C/5S/6/6+/6S/6S+/7/7+, iPad 1/2/3/4/Mini/Mini 3/Mini 4/Air/Air 2/Pro and Apple TV 2G/3G/4G running up to firmware 10.3 on Linux, Mac OS X and Windows.

**Comment by NextOneWxf** [comment]
![image](https://user-images.githubusercontent.com/4550421/42996174-5ec3c020-8c45-11e8-9cb8-60eb526b26a3.png)
@ @YurRee

**Comment by YurRee** [comment]
感谢反馈，请参阅 [READE - 常见问题](https://github.com/meituan/lyrebird-ios#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 获取更多帮助信息，Thanks. :+1:

**Comment by YurRee** [comment]
@NextOneWxf 如果没有问题我先关闭 issue 了。后续如果有任何新的问题，欢迎打开新的 issue 🥇
